#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1 && python3 -c 'pass' 2>/dev/null; then
	py3clean -p svlang 
else
	dpkg -L svlang | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
